apiVersion: v1
kind: Service
metadata:
  name: {{ include "cyclecloud.fullname" . }}
  labels:
    {{- include "cyclecloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8443
  selector:
    {{- include "cyclecloud.selectorLabels" . | nindent 4 }}
